DROP TABLE BOOKING;
DROP TABLE GUEST;
DROP TABLE APARTMENT;
DROP TABLE APARTMENT_DESCRIPTION;
DROP TABLE HOTEL;
DROP TABLE HOTEL_DESCRIPTION;
DROP TABLE CITY;

DROP SEQUENCE APART_APART_ID_SEQ;
DROP SEQUENCE APART_DESC_APART_DESC_ID_SEQ;
DROP SEQUENCE CITY_CITY_ID_SEQ;
DROP SEQUENCE GUEST_GUEST_ID_SEQ;
DROP SEQUENCE HOTEL_DESC_HOTEL_DESC_ID_SEQ;
DROP SEQUENCE HOTEL_HOTEL_ID_SEQ;
